### ISSUE TITLE
python3-rosdep2がなくなる

### ISSUE THREAD

**Issue by grgrmawal** [kimushun1101/tb3_controller_cpp#2]
ubuntu22.04で環境構築の最初「2. Git のインストールとROS 2 環境の準備」という項目で書かれている内容をそのまま実行すると以下のようなエラー文がでます。
~~~
unable to process source [file:///usr/share/python3-rosdep2/debian.yaml]:
	<urlopen error [Errno 2] No such file or directory
~~~
おそらくrun.sh内部でpython3-rosdepをインストールする際に自動でpython3-rosdep2が削除されるためだと思われます。

**Comment by kimushun1101** [comment]
私の環境では再現できないのですが、`./run.sh` コマンド実行時の挙動ということでよろしいでしょうか？
pyenv やconda などのPython 環境を作られていたりしませんでしょうか？

**Comment by grgrmawal** [comment]
pyenvは切っているのですがそれでも発生します。python3-rosdep2をaptでインストールした後にpython3-rosdepをaptでインストールしてもpython3-rosdep2が消える現象を確認しました。

**Comment by kimushun1101** [comment]
根本的な解決ではありませんが，ROS 2 や rosdep のインストール（環境構築）は個々のユーザに任せる形をとりたいと思います．README.md も，公式ページに誘導するような形に変更しました．
